packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Dev tooling
  eslint: ^8.57.0
  prettier: ^3.5.3
  typescript: ^5.8.2

  # Misc
  zod: ^3.24.2
  superjson: ^2.2.2

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.69.0
  "@trpc/client": ^11.0.0
  "@trpc/tanstack-react-query": ^11.0.0
  "@trpc/server": ^11.0.0

  # React
  react: 18.3.1
  react-dom: 18.3.1
  "@types/react": 18.3.1
  "@types/react-dom": 18.3.1
